### ISSUE TITLE
Adding a second USDZ crashes F3d

### ISSUE THREAD

**Issue by gerroon** [f3d-app/f3d#1834]
**Describe the bug**
It seems like the window only loads one USD, consequent USD loads crashes the app

**To Reproduce**
Use the USDs in the zip
load one of them.
Drag and drop the other one once the window loads

**Expected behavior**
It shouldn't crash

**System Information:**
 - OS: Win 11
 - GPU and GPU driver: RTX 2070

**F3D Information**
Paste the content of `f3d --version`: `bin\f3d.exe --version` prints nothing 
This is the zip `F3D-2.5.1-220-g55e20f54-Windows-x86_64.zip`

[Downloads.zip](https://github.com/user-attachments/files/18241290/Downloads.zip)

**Comment by mwestphal** [comment]
I  reproduce using the binary on Linux, but not in my local build. Investigation needed.

**Comment by mwestphal** [comment]
I reproduce with ANY .usdz. .usd does not have this issue.

**Comment by mwestphal** [comment]
may be a duplicate of https://github.com/f3d-app/f3d/issues/1499

**Comment by Meakk** [comment]
The file `Table.usdz` outputs this warning when opening with `--verbose`:
```
Found material bindings on prim at path (/scene/Meshes/Sketchfab_model/root/GLTF_SceneRootNode/Cube_0/Object_4/Object_0) but MaterialBindingAPI is not applied on the prim
```

When opening it AFTER `Longsword.usdz`, it crashes in:
```
#0  0x00007fffea3636fe in pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr::PostWarning(pxrInternal_v0_24__pxrReserved__::TfEnum, char const*, pxrInternal_v0_24__pxrReserved__::TfCallContext const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::any, bool) const () from /usr/lib/libusd_ms.so
#1  0x00007fffea363a8a in pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr::WarningHelper::Post(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /usr/lib/libusd_ms.so
#2  0x00007fffea363b82 in pxrInternal_v0_24__pxrReserved__::Tf_PostWarningHelper(pxrInternal_v0_24__pxrReserved__::TfCallContext const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libusd_ms.so
#3  0x00007fffea363c8a in pxrInternal_v0_24__pxrReserved__::Tf_PostWarningHelper(pxrInternal_v0_24__pxrReserved__::TfCallContext const&, char const*, ...) ()
   from /usr/lib/libusd_ms.so
#4  0x00007fffeac2ed08 in pxrInternal_v0_24__pxrReserved__::UsdShadeMaterialBindingAPI::BindingsAtPrim::BindingsAtPrim(pxrInternal_v0_24__pxrReserved__::UsdPrim const&, pxrInternal_v0_24__pxrReserved__::TfToken const&, bool) () from /usr/lib/libusd_ms.so
....
```
Looking at the code, it seems like it crashes exactly where the warning is emitted.
See https://github.com/PixarAnimationStudios/OpenUSD/blob/9b0c13b2efa6233c8a4a4af411833628c5435bde/pxr/usd/usdShade/materialBindingAPI.cpp#L669

`Longsword.usdz` has a similar warning too

I tried chaining several usdz files without this warning, and it works just fine.

**Comment by Meakk** [comment]
I'm moving this issue to 3.1

**Comment by mwestphal** [comment]
Confirmed fixed in F3D 3.1.0-RC3 !
