### ISSUE TITLE
[1.3.0] Application aborts

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#415]
**Describe the bug**
```
(gdb) r
Starting program: /usr/local/bin/f3d

Program received signal SIGABRT, Aborted.
Sent by thr_kill() from pid 88961 and user 1001.
thr_kill () at thr_kill.S:4
4       in thr_kill.S
(gdb) bt
#0  thr_kill () at thr_kill.S:4
#1  0x0000000800588104 in __raise (s=s@entry=6) at /disk-samsung/freebsd-src/lib/libc/gen/raise.c:52
#2  0x0000000800638dc9 in abort () at /disk-samsung/freebsd-src/lib/libc/stdlib/abort.c:67
#3  0x000000080186a8a3 in vtkXOpenGLRenderWindow::CreateAWindow() () from /usr/local/lib/libvtkRenderingOpenGL2-9.1.so.1
#4  0x000000080186abb3 in vtkXOpenGLRenderWindow::WindowInitialize() () from /usr/local/lib/libvtkRenderingOpenGL2-9.1.so.1
#5  0x000000080186ae42 in vtkXOpenGLRenderWindow::Start() () from /usr/local/lib/libvtkRenderingOpenGL2-9.1.so.1
#6  0x00000008018a5f06 in vtkXRenderWindowInteractor::Initialize() () from /usr/local/lib/libvtkRenderingUI-9.1.so.1
#7  0x000000080030f6b2 in ?? () from /usr/local/bin/../lib/libf3d.so
#8  0x000000080030e3b2 in ?? () from /usr/local/bin/../lib/libf3d.so
#9  0x0000000800304b18 in f3d::engine::engine(f3d::window::Type) () from /usr/local/bin/../lib/libf3d.so
#10 0x0000000000263f76 in ?? ()
#11 0x0000000000265c82 in ?? ()
#12 0x0000000000220500 in ?? ()
#13 0x0000000000220400 in ?? ()
#14 0x0000000000000000 in ?? ()
(gdb) 
```

**To Reproduce**
regular build, install, run

**System Information:**
 - OS: FreeBSD 13.1

**F3D Information**
Paste the content of `f3d --version`:
```
$ f3d --version
f3d 1.3.0

F3D - A fast and minimalist 3D viewer
Version: 1.3.0.
Build date: 2022-09-07 16:40:22.
Build system: FreeBSD amd64.
Compiler: Clang 14.0.5.
External rendering module: OFF.
Raytracing module: OFF.
Exodus module: ON.
OpenCASCADE module: OFF.
Assimp module: OFF.
Alembic module: OFF.
VTK version: 9.1.0 (build 0).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Comment by mwestphal** [comment]
We build f3d with vtk 9.1 in our ci, so this is definitely unexpected. Are you able to build and run any VTK example?

**Comment by mwestphal** [comment]
No worries

**Comment by mwestphal** [comment]
@yurivict please note there is a 1.3.1 out.

**Comment by yurivict** [comment]
@mwestphal Thanks for letting me know!
