### ISSUE TITLE
Draco segfault on coloring

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#529]
**Describe the bug**
Draco segfault on coloring

**To Reproduce**
 1. Open the file using `f3d --dry-run suzanne.drc`
 2. press S
 3. segfault

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid

Thread 1 "f3d" received signal SIGABRT, Aborted.
0x00007ffff792264c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff792264c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff78d2958 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff78bc53d in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7c22833 in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff7c2ecfc in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff7c2ed69 in std::terminate () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff7c2efcd in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff7db2168 <typeinfo for std::logic_error>, dest=0x7ffff7c465c0 <std::logic_error::~logic_error()>)
    at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffff7c253b7 in std::__throw_logic_error (__s=0x5555556350e8 "basic_string: constructio n from null is not valid") at /usr/src/debug/gcc/libstdc++-v3/src/c++11/functexcept.cc:70
#8  0x0000555555585c4e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> > (this=0x7fffffffe410, __s=0x0, __a=...)
    at /usr/include/c++/12.2.0/bits/basic_string.h:639
#9  0x00007ffff7f3c787 in vtkF3DRendererWithColoring::GetColoringArrayName[abi:cxx11]() (this=0x555555f59ea0)
    at /home/glow/dev/f3d/fsb/build/superbuild/f3d/src/library/VTKExtensions/Rendering/vtkF3DRendererWithColoring.cxx:250
#10 0x00007ffff7f3c55d in vtkF3DRendererWithColoring::SetColoring (this=0x555555f59ea0, useCellData=false, arrayName="", component=-1)
    at /home/glow/dev/f3d/fsb/build/superbuild/f3d/src/library/VTKExtensions/Rendering/vtkF3DRendererWithColoring.cxx:224
#11 0x00007ffff7eee014 in f3d::detail::window_impl::UpdateDynamicOptions (this=0x555555708730) at /home/glow/dev/f3d/fsb/build/superbuild/f3d/src/library/src/window_impl.cxx:293
#12 0x00007ffff7eeec67 in f3d::detail::window_impl::render (this=0x555555708730) at /home/glow/dev/f3d/fsb/build/superbuild/f3d/src/library/src/window_impl.cxx:340
#13 0x000055555561b733 in F3DStarter::Start (this=0x7fffffffe6f8, argc=2, argv=0x7fffffffe838) atzed /home/glow/dev/f3d/fsb/build/superbuild/f3d/src/application/F3DStarter.cxx:301
#14 0x000055555561f437 in main (argc=2, argv=0x7fffffffe838) at /home/glow/dev/f3d/fsb/build/supeannrbuild/f3d/src/application/main.cxx:13
(gdb) q
```

**Comment by Meakk** [comment]
Fixed by #530
