### ISSUE TITLE
Segfault when volume rendering 2D datasets

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#99]
Steps to reproduce:

- ./bin/f3d logo.tif -v
- press v repeatedly and interact at te same time until it segfault
```

Thread 1 "f3d" received signal SIGABRT, Aborted.
0x00007ffff18b4d22 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff18b4d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff189e862 in abort () from /usr/lib/libc.so.6
#2  0x00007fffee93263d in ?? () from /usr/lib/dri/iris_dri.so
#3  0x00007fffef4557f4 in ?? () from /usr/lib/dri/iris_dri.so
#4  0x00007fffee9bae84 in ?? () from /usr/lib/dri/iris_dri.so
#5  0x00007fffee9541e1 in ?? () from /usr/lib/dri/iris_dri.so
#6  0x00007ffff03b1c3c in ?? () from /usr/lib/libGLX_mesa.so.0
#7  0x00007ffff673f029 in vtkXOpenGLRenderWindow::Frame (this=0x5555555bbc70)
    at /home/glow/work/vtk/vtk1/src/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx:331
#8  0x00007ffff577668e in vtkRenderWindow::CopyResultFrame (this=0x5555555bbc70) at /home/glow/work/vtk/vtk1/src/Rendering/Core/vtkRenderWindow.cxx:567
#9  0x00007ffff577504b in vtkRenderWindow::Render (this=0x5555555bbc70) at /home/glow/work/vtk/vtk1/src/Rendering/Core/vtkRenderWindow.cxx:308
#10 0x00007ffff665ae65 in vtkOpenGLRenderWindow::Render (this=0x5555555bbc70)
    at /home/glow/work/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx:2265
#11 0x00007ffff6744958 in vtkXOpenGLRenderWindow::Render (this=0x5555555bbc70)
    at /home/glow/work/vtk/vtk1/src/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx:1583
#12 0x00007ffff577ebce in vtkRenderWindowInteractor::Render (this=0x5555555bc260)
    at /home/glow/work/vtk/vtk1/src/Rendering/Core/vtkRenderWindowInteractor.cxx:182
#13 0x00007ffff6477404 in vtkXRenderWindowInteractor::DispatchEvent (this=0x5555555bc260, event=0x7fffffffdd00)
    at /home/glow/work/vtk/vtk1/src/Rendering/UI/vtkXRenderWindowInteractor.cxx:503
#14 0x00007ffff6476237 in vtkXRenderWindowInteractor::StartEventLoop (this=0x5555555bc260)
    at /home/glow/work/vtk/vtk1/src/Rendering/UI/vtkXRenderWindowInteractor.cxx:257
#15 0x00007ffff577ed6f in vtkRenderWindowInteractor::Start (this=0x5555555bc260)
    at /home/glow/work/vtk/vtk1/src/Rendering/Core/vtkRenderWindowInteractor.cxx:230
#16 0x00007ffff7cd88db in F3DLoader::Start (this=0x7fffffffe1c0, argc=2, argv=0x7fffffffe948, image=0x0) at /home/glow/work/f3d/src/src/F3DLoader.cxx:215
#17 0x000055555555628d in main (argc=2, argv=0x7fffffffe948) at /home/glow/work/f3d/src/src/main.cxx:17
```

**Comment by Meakk** [comment]
Where is logo.vti? I cannot reproduce with another vti file

**Comment by mwestphal** [comment]
sorry, typo, logo.tif

**Comment by Meakk** [comment]
I do not reproduce

**Comment by mwestphal** [comment]
me neither, closing
